Repository bancodetempo/bdt-backend, pull requests merged in 2020-09, with the labels that each got.

#5 cofirming and executing order transaction through django admin
  orders/admin.py
  orders/migrations/0004_auto_20200903_1343.py
  orders/models.py
  orders/serializers.py
  orders/tests.py
Labels: enhancement

#6 Fix/autocomplete
  .gitignore
  bdtapi/settings/base.py
  user/filters.py
  user/tests.py
Labels: bug

#7 Ensuring user account has funds before creating order
  orders/serializers.py
  orders/tests/__init__.py
  orders/tests/tests_order_api.py
  orders/tests/tests_order_manager.py
Labels: enhancement

#9 using SearchFilter class to search users
  user/views.py
Labels: refactor

#8 validating if order requester and grantor are not the same
  orders/serializers.py
  orders/tests/tests_order_api.py
Labels: enhancement
